import turtle
turtle.Screen().setup(600,600)
turtle.shape("turtle")
turtle.penup()
turtle.goto(-300,100)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
for i in range(2):
	turtle.forward(200)
	turtle.left(90)
	turtle.forward(100)
	turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.goto(-260,120)
turtle.color("white")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.goto(-260,125)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()
turtle.penup()
turtle.goto(-100,160)
turtle.pendown()
turtle.color("white")
turtle.begin_fill()
for i in range(5):
	turtle.forward(25)
	turtle.left(144)
turtle.end_fill()

turtle.hideturtle()
turtle.done()